apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CLUSTER_NAME
  region: AWS_REGION
  version: "1.17"
  
vpc:
  subnets:
    public:
      pub-02: { id: subnet-044bfb49b2f2efd8c }
      pub-01: { id: subnet-0eb199c0007a446ee }
    private:
      pvt-02: { id: subnet-00670b82854d79fed }
      pvt-03: { id: subnet-06466bd7cde8b01f6 }

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

managedNodeGroups:
  - name: NODEGROUP_NAME1
    instanceType: t2.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    ssh:
       PublicKeyName: PEM_KEY

nodeGroups:
  - name: NODEGROUP_NAME2
    amiFamily: WindowsServer2019FullContainer
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    ssh:
       PublicKeyName: PEM_KEY
